### ISSUE TITLE
Droppa処理中のプログレスバー

### ISSUE THREAD

**Issue by ryosukemaehira** [FIRST-PENGUIN/droppa_client#4]
### WHAT
プログレスバーで、どれくらいDroppa化できているのか、あとどれくらいDroppa化に時間がかかるのか、を表示

### WHEN
- ディレクトリのDroppa化時

### WHY
ユーザーのストレス軽減のため

## 詳細

最終的な実装としては、サーバー側から非同期で進捗状況を受け取り、
### モックアップ
まだない

## 実装優先度

【高】/中/低

****
# 実装方法

## 新しく作るComponent
dpProgressBar のコンポーネントは、別ファイルで定義し、export し、DpNavigationComponent にて import しておく。

## Componentの呼び出し
DpNavigationComponent で定義している、 Droppaボタンのクリックで動く `makeDroppa` 関数の中から、dpProgressBar のコンポーネントを呼び出す。

## Component の動き
~~プログレスバーのJSX を return する。~~
プログレスバーのモーダルのJSX を return する。
API側からPythonの解析の進捗を受け取り（←後日実装）、プログレスバーはそれに連動して動く。

**Comment by ryosukemaehira** [comment]
/design
作ってそこでマークアップだけしてます

![image](https://cloud.githubusercontent.com/assets/13879825/23983731/10eaea82-0a59-11e7-94dd-808f3d068bac.png)

api 側から進捗パーセンテージ受け取ったら良いように作っておりますん

**Comment by ryosukemaehira** [comment]
/design
作ってそこでマークアップだけしてます

![image](https://cloud.githubusercontent.com/assets/13879825/23983731/10eaea82-0a59-11e7-94dd-808f3d068bac.png)

api 側から進捗パーセンテージ受け取ったら良いように作っておりますん

**Comment by ryosukemaehira** [comment]
いや、これモーダルにすべきじゃないな。
メインコンテンツ丸々目隠しした方がいいのか…？

**Comment by ryosukemaehira** [comment]
# 実装方法
DpNavigationComponent で定義している、 Droppaボタンのクリックで動く `makeDroppa` 関数の中から、dpProgressBar のコンポーネントを呼び出す。
dpProgressBar のコンポーネントは、別ファイルで定義し、export し、DpNavigationComponent にて import しておく。

**Comment by sa-inu** [comment]
`makeDroppa` メソッドでは `そのディレクトリをdroppa化する` ためのものですね！
いきなりプログレスバーの仕様策定に入ってますが、その前段階はどうなってますか？
あれ、そもそも僕は、アップロード処理はドロップエリアをこちらで実装せずにdriveのシステムを使うという認識だったのでこのプログレスバーは実装しないと思ってました。
明日もう一度すり合わせましょう。

**Comment by sa-inu** [comment]
あ、失礼しました！
これは最初にディレクトリをドロッパ化した際の仕様ですか！
勘違いしてました。 🙇

**Comment by sa-inu** [comment]
>Droppaディレクトリへのファイルドロップ時

https://github.com/FIRST-PENGUIN/droppa_client/issues/4#issuecomment-287046316 は上記に対するものです。

**Comment by ryosukemaehira** [comment]
あ、そっすね！
>最初にディレクトリをドロッパ化した際の仕様

です！ややこしくてすいませｎ！
