### ISSUE TITLE
ローディングアニメーション

### ISSUE THREAD

**Issue by ryosukemaehira** [FIRST-PENGUIN/droppa_client#6]
## 概要
Droppaの拡張機能を起動した時に動かすローディングアニメーション

## モックアップ
こういうやつ
<img width="1280" alt="2017-03-17 10 42 27" src="https://cloud.githubusercontent.com/assets/13879825/24025732/ac4d5158-0aff-11e7-914e-2c7c638fba90.png">

## 実装優先度

中

**Comment by sa-inu** [comment]
これ一旦下げます
