### ISSUE TITLE
Droppaにドロップした時のアニメーション

### ISSUE THREAD

**Issue by ryosukemaehira** [FIRST-PENGUIN/droppa_client#7]
## 概要
ユーザーがDroppaステータスを持ったディレクトリにファイルをドロップした時のアニメーション

サーバー側で起こっていることとしては、Driveにファイルが保存されて、そのファイルを適切な位置に再配置していく作業

## 実装優先度

中

**Comment by katsuya0515** [comment]
>プログレスバーとか無くてもユーザーにはストレスはさほど無い
>理由：実装が上手く行けば、かかる時間も普通にDriveに保存する時間と大差ないと考えられるため。

処理順番的に、アップロード→リンク取得→サーバーtalk→Vison API→パース→ファイル移動となるので、アップロードのあとにそれなりに処理がかかると思います。ちなみに今ベンチーマークしてみましたが、Vison APIは1ファイルだいたい2-3秒かかりそうです。

実際にファイルをドロップしてみて、Droppaされる感じを見てみないとわからないといえばわからないですが。使う使わないはUXで判断するとして、実装はしておいた方が良いかなと。

**Comment by ryosukemaehira** [comment]
>Vison APIは1ファイルだいたい2-3秒かかりそう

うおおおお
そんなにかかるんですね。

何か歯切れのいいアニメーション作ります！

**Comment by ryosukemaehira** [comment]
# メモ
**20170403mtgより**
プログレスバーは削除して、Droppaボタンを横に小さくアニメーションを表示することになった。
完了したらアニメーションを削除し、トーストで通知
